export const GET_LATEST_COIN_DATA_START = 'GET_LATEST_COIN_DATA_START';
export const GET_LATEST_COIN_DATA_SUCCESS = 'GET_LATEST_COIN_DATA_SUCCESS';
export const GET_LATEST_COIN_DATA_FAILURE = 'GET_LATEST_COIN_DATA_FAILURE';
export const SORT_BY_NAME = 'SORT_BY_NAME';
export const SELECT_COIN_GRAPH = 'SELECT_COIN_GRAPH';
